### ISSUE TITLE
[BUG] [Android] Firefox nightly is crash while click by link on video

### ISSUE THREAD

**Issue by vitonsky** [Semro/syncwatch#26] opened 2022-03-08 20:23 UTC
Reproduce steps:
- Open addon popup in firefox nightly on android
- Connect to server
- Share video from another device
- Tap on link

Expected behavior:
- Open tab with video

Actual behavior:
- Browser will down

**Comment by Semro** [comment] 2022-03-11 22:39
I've reported it to Firefox Nightly repository: https://github.com/mozilla-mobile/fenix/issues/24228

**Comment by Semro** [comment] 2022-06-18 18:26
Bug has been fixed on their side: https://bugzilla.mozilla.org/show_bug.cgi?id=1759560

However, opening video in popup will not sync it (probably my side, but I don't have time to debug it right now), so I made a [workaround](https://github.com/Semro/syncwatch/commit/214d4d69d104edcba5a5bf1274f2061269842f15) to open video in a new tab. The problem is, Firefox will not focus on that tab, and you will need to
 - close the popup window after clicking a link
 - or you can tap on notification, and then it will focus on created tab.
 
I'm also noticed that video on YouTube opened in popup won't show, only black screen in a player, so this workaround could be a better option than trying to sync videos in popup window.

**Closed by Semro** 2022-06-18 18:26 UTC

**Comment by vitonsky** [comment] 2022-06-18 18:32
@Semro it's very good news. Thank you for improve the world. Syncwatch is one of most used extensions in my browser
